// Example site config: tsungi.online, the first site to use colorsbymax.
// Pass it to <ThemeProvider config={tsungiConfig}> and use the same storageKey in the
// pre-paint script. The default theme is Tsungi's shipped colours.

export default {
  siteName: 'Tsungi',
  storageKey: 'tsungi-theme',
  defaultTheme: {
    name: 'Tsungi Orchid',
    tokens: {
      primary: '#c67cde',
      'primary-dark': '#45256d',
      'primary-alt': '#c27aff',
      'on-primary': '#ffffff',
      background: '#fdfcfd',
      surface: '#ffffff',
      secondary: '#ebdbf0',
      'on-secondary': '#631f7a',
      accent: '#f0e0f5',
      'on-accent': '#8529a3',
      border: '#e8e0eb',
      shadow: '#000000',
      ink: '#28222a',
      'ink-secondary': '#78677e',
      'ink-muted': '#78677e',
      success: '#00c950',
      warning: '#fe9a00',
      danger: '#fb2c36',
      info: '#2b7fff',
      'data-1': '#2b7fff',
      'data-2': '#00bc7d',
      'data-3': '#f6339a',
      'data-4': '#ff6900',
      'data-5': '#6a7282',
      'data-6': '#8e51ff',
      'data-7': '#00b8db',
      'data-8': '#7ccf00',
      'app-background': '#eae1ea',
      'app-input': '#e0d1e0',
      'app-border': '#d6c2d5',
      'app-primary': '#c0a5c0',
      'app-shadow-dark': '#dac8d9',
      'app-shadow-light': '#fbf9fb',
      'app-ink': '#2e2e2e',
      'app-ink-muted': '#737373',
    },
  },
  usage: {
    primary: 'Buttons, mission band, links, focus rings',
    'primary-dark': 'Logo wordmark',
    'data-1': 'Typing Game icon, Co-Founder label',
    'data-2': 'Scheduling icon, Developer label',
    'app-background': 'Sign in / sign up pages',
  },
}
