// Builds src/icons.jsx: the few Lucide icons the switcher uses, copied in as plain SVG
// components so the package doesn't depend on an icon library (and can't end up with a second
// copy of one next to the site's own). lucide-react is only a dev dependency, read from here.
//
//   npm run icons
//
// Lucide is ISC licensed (some icons MIT, from Feather); the notice is in THIRD_PARTY_NOTICES.md.

import { readFileSync, writeFileSync } from 'node:fs'
import { createRequire } from 'node:module'
import { dirname, join } from 'node:path'
import { pathToFileURL } from 'node:url'

const ICONS = [
  'AlertTriangle', 'ArrowLeft', 'Check', 'CheckCircle2', 'ChevronRight', 'Copy', 'Download', 'Globe',
  'ImageUp', 'Loader2', 'Monitor', 'Moon', 'Paintbrush', 'Palette', 'RotateCcw', 'ScanLine', 'Settings',
  'Shuffle', 'Sun', 'Trash2', 'Upload', 'UserRound', 'Wand2', 'X', 'ScanSearch', 'Contrast', 'ClipboardPaste', 'ToggleRight', 'LibraryBig', 'Minus', 'Plus',
]

const require = createRequire(import.meta.url)
const root = dirname(require.resolve('lucide-react/package.json'))
const { version } = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'))
const esm = join(root, 'dist/esm')
const index = readFileSync(join(esm, 'lucide-react.mjs'), 'utf8')

// Export name -> icon module, from lines like `export { default as X, ... } from './icons/x.mjs'`.
const files = {}
for (const [, names, file] of index.matchAll(/export \{([^}]*)\} from '(\.\/icons\/[^']+)'/g)) {
  for (const part of names.split(',')) {
    const m = part.trim().match(/^default as (\w+)$/)
    if (m) files[m[1]] = file
  }
}

const out = []
for (const name of ICONS) {
  if (!files[name]) throw new Error(`No Lucide icon named ${name}`)
  // Each icon module exports its shapes as __iconData.node: [tag, attrs] pairs. React keys go.
  const { __iconData } = await import(pathToFileURL(join(esm, files[name])).href)
  const shapes = __iconData.node.map(([tag, { key, ...attrs }]) => [tag, attrs])
  const slug = files[name].replace(/^\.\/icons\/|\.mjs$/g, '')
  out.push(`export const ${name} = icon('${slug}', ${JSON.stringify(shapes)})`)
}

writeFileSync(
  new URL('../src/icons.jsx', import.meta.url),
  `// Generated by scripts/build-icons.mjs from lucide-react ${version}. Do not edit.
// Lucide icons (ISC licence; some MIT, from Feather): see THIRD_PARTY_NOTICES.md.

import { createElement } from 'react'

/** A Lucide-style icon: 24×24, drawn with currentColor strokes, sized by className. */
function icon(slug, shapes) {
  const Icon = ({ className = '', ...props }) => (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      className={\`lucide lucide-\${slug} \${className}\`.trim()}
      {...props}
    >
      {shapes.map(([tag, attrs], i) => createElement(tag, { key: i, ...attrs }))}
    </svg>
  )
  Icon.displayName = slug
  return Icon
}

${out.join('\n')}
`,
)
console.log(`Wrote ${ICONS.length} icons from lucide-react ${version}`)
