// Builds src/panel-css.generated.js: the switcher's own stylesheet, compiled from src/panel.css
// with Tailwind and exported as a string. ThemeSwitcher puts it inside its shadow root, so the
// panel looks the same on any site, whether or not the site uses Tailwind.
//
//   npm run css
//
// The demo's Vite config also runs this on start and whenever the panel's source changes.
// Output is adjusted for a shadow root:
// - rem becomes px, so a host page that changes the root font size can't rescale the panel;
// - @property rules are dropped (browsers ignore them inside shadow roots) and Tailwind's
//   fallback defaults for those variables are applied unconditionally instead.

import { execFileSync } from 'node:child_process'
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = fileURLToPath(new URL('..', import.meta.url))
const INPUT = join(ROOT, 'src/panel.css')
const OUT = join(ROOT, 'src/panel-css.generated.js')
const CLI = join(ROOT, 'node_modules/@tailwindcss/cli/dist/index.mjs')

export function compilePanelCss() {
  const dir = mkdtempSync(join(tmpdir(), 'colorsbymax-'))
  try {
    const file = join(dir, 'panel.css')
    execFileSync(process.execPath, [CLI, '-i', INPUT, '-o', file, '--minify'], { cwd: ROOT, stdio: 'pipe' })
    return adaptForShadowRoot(readFileSync(file, 'utf8'))
  } finally {
    rmSync(dir, { recursive: true, force: true })
  }
}

function adaptForShadowRoot(css) {
  return css
    .replace(/(\d*\.?\d+)rem\b/g, (_, n) => `${+(n * 16).toFixed(3)}px`)
    .replace(/@property\s+[\w-]+\s*\{[^}]*\}/g, '')
    .replace(/(@layer properties\s*\{\s*@supports\s*)[^{]+/, '$1(display:block)')
}

/** Writes the generated module; returns true when its contents changed. */
export function buildPanelCss() {
  const source =
    '// Generated by scripts/build-css.mjs from src/panel.css. Do not edit.\n' +
    `export default ${JSON.stringify(compilePanelCss())}\n`
  let previous = null
  try {
    previous = readFileSync(OUT, 'utf8')
  } catch {}
  if (previous === source) return false
  writeFileSync(OUT, source)
  return true
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  buildPanelCss()
  console.log(`Wrote ${OUT}`)
}
